name: main
'on':
  push:
    branches:
      - main
env:
  FOO: BAR
jobs:
  checks:
    uses: ./.github/workflows/onchange.yml
  main:
    name: main
    runs-on: ubuntu-latest
    needs:
      - checks
    steps:
      - name: semantic-release
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
        run: >-
          npm init -y && npm install -D   "semantic-release"  
          "@semantic-release/commit-analyzer"  
          "@semantic-release/release-notes-generator"  
          "@semantic-release/github"   "@semantic-release/git"  
          "@semantic-release/exec" && ./node_modules/.bin/semantic-release
