name: main
"on":
  push:
    branches:
      - main
jobs:
  checks:
    uses: ./.github/workflows/onchange.yml
    secrets: inherit
  setup:
    uses: ./.github/workflows/setup.yml
    secrets: inherit
  main:
    name: main
    runs-on: ubuntu-latest
    needs:
      - checks
      - setup
    steps:
      - name: release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
        run: pnpm semantic-release
