name: main
"on":
  push:
    branches:
      - main
jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0 # Necessary to access local action
      - name: setup
        id: setup
        uses: ./.github/actions/setup
      - name: checks
        id: checks
        uses: ./.github/actions/checks
      - name: release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
        run: pnpm semantic-release
