name: onchange
"on":
  - pull_request

jobs:
  check:
    name: onchange
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2 # Necessary to access local action
      - name: setup
        id: setup
        uses: ./.github/actions/setup
      - name: checks
        id: checks
        uses: ./.github/actions/checks
      - name: release dry-run
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
        run: pnpm semantic-release --dry-run
