name: onchange
"on":
  - workflow_call
  - pull_request
jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    secrets: inherit
  check:
    name: onchange
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: release dry-run
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
        run: pnpm semantic-release --dry-run
